### ISSUE TITLE
[PlayError] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by suptower** [distubejs/ytsr#1]
When using ytsr version 1.1.10, I am not able to search songs. 
Using 1.1.9 is fine.

```
..\node_modules\@distube\ytsr\lib\util.js:311
  Object.keys(obj).find(p => p.toLowerCase() === prop.toLowerCase()) || null;
         ^

TypeError [PlayError]: The Weeknd - Blinding Lights
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at findPropKeyInsensitive (...\node_modules\@distube\ytsr\lib\util.js:311:10)
    at getPropInsensitive (...\node_modules\@distube\ytsr\lib\util.js:314:15)
    at exports.checkArgs (...\node_modules\@distube\ytsr\lib\util.js:87:18)
    at module.exports (...\@distube\ytsr\lib\main.js:27:21)
    at _DisTube.search (...\node_modules\distube\dist\index.js:3003:52)
    at _DisTube.search (...\node_modules\distube\dist\index.js:3016:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _DisTube.play (...\node_modules\distube\dist\index.js:2906:19)

Node.js v18.14.1
```

**Comment by kratosrog** [comment]
same, actually even the ^1.1.9 giving same error.

`/app/node_modules/@distube/ytsr/lib/util.js:311`
`Object.keys(obj).find(p => p.toLowerCase() === prop.toLowerCase()) || null;`
`^`
`TypeError: Cannot convert undefined or null to object`
`at Function.keys (<anonymous>)`
`at findPropKeyInsensitive (/app/node_modules/@distube/ytsr/lib/util.js:311:10)`
`at getPropInsensitive (/app/node_modules/@distube/ytsr/lib/util.js:314:15)`
`at exports.checkArgs (/app/node_modules/@distube/ytsr/lib/util.js:87:18)`
`at module.exports (/app/node_modules/@distube/ytsr/lib/main.js:27:21)`
`at Object.run (/app/commands/fun/youtube.js:15:13)`
`at Object.execute (/app/events/messageCreate.js:391:25)`
`at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
`Node.js v18.12.1`
